<<<<<<< HEAD
version: 2
jobs:   
  build:
    machine: true
    steps:
      - add_ssh_keys:
          fingerprints: 
            - "e4:59:fe:67:0e:e9:6a:cb:f5:c1:2c:24:40:3d:ab:8d"
      - checkout
      - run: docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run: docker build -t mimorgal/hola-docker:$CIRCLE_SHA1 .
      - run: docker push mimorgal/hola-docker:$CIRCLE_SHA1
      - run: ssh -o StrictHostKeyChecking=no ubuntu@18.237.107.100 "/bin/bash /home/ubuntu/deploy.sh $CIRCLE_SHA1"

=======
# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Use a package of configuration called an orb.
orbs:
  # Declare a dependency on the welcome-orb
  welcome: circleci/welcome-orb@0.4.1
# Orchestrate or schedule a set of jobs
workflows:
  # Name the workflow "welcome"
  welcome:
    # Run the welcome/run job in its own container
    jobs:
      - welcome/run
>>>>>>> 9b34e3c05f70a77dc8a593c644c2a21ec4fa0b5e
