version: 2
jobs:   
  build:
    machine: true
    steps:
      - add_ssh_keys:
          fingerprints: 
            - "17:55:eb:56:09:af:0e:f0:b4:63:de:8c:f5:37:60:c4"
      - checkout
      - run: docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run: docker build -t mimorgal/hola-docker:$CIRCLE_SHA1 .
      - run: docker push mimorgal/hola-docker:$CIRCLE_SHA1
      - run: ssh -o StrictHostKeyChecking=no ubuntu@54.188.89.173 "/bin/bash /home/ubuntu/deploy.sh $CIRCLE_SHA1"
